import Link from "next/link";
import { Footer } from "@/components/Footer";

export const metadata = {
  title: "Privacy Policy - Storezn",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen flex flex-col bg-white">
      <main className="flex-1 max-w-2xl mx-auto px-4 sm:px-6 py-16 space-y-10">
        <div>
          <Link href="/" className="text-sm text-brand-600 hover:underline">Storezn</Link>
          <h1 className="text-2xl sm:text-3xl font-semibold tracking-tight text-slate-900 mt-4">Privacy Policy</h1>
          <p className="text-sm text-slate-700 mt-1">Last updated September 2026</p>
        </div>

        <div className="space-y-8 text-sm text-slate-700 leading-relaxed">
          <p>
            This policy explains what information Storezn (&quot;we&quot;, &quot;the platform&quot;) collects when you use it as a
            vendor or a customer, why we collect it, and what we do with it. It should be read together with the{" "}
            <Link href="/terms" className="text-brand-600 hover:underline">Terms of Service</Link>.
          </p>

          <section className="space-y-2">
            <h2 className="text-base font-semibold text-slate-900">1. Information you give us</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li><span className="font-medium">Account details</span> — your name, email address, phone number, and a hashed (never plain-text) password.</li>
              <li><span className="font-medium">Vendor identity</span> — your National Identification Number (NIN), submitted for verification before a store can sell.</li>
              <li><span className="font-medium">Store &amp; catalogue data</span> — your store name, products, prices, stock, categories, and settings.</li>
              <li><span className="font-medium">Order &amp; delivery data</span> — items ordered, delivery address, and buyer contact details for each order.</li>
              <li><span className="font-medium">Payout details</span> — the bank account a vendor links to receive payments.</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-semibold text-slate-900">2. Information collected automatically</h2>
            <p>When you use the platform we also record, for security and abuse-prevention purposes:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li><span className="font-medium">Connection data</span> — your IP address and the approximate time of a request.</li>
              <li>
                <span className="font-medium">Device identifier</span> — a random identifier generated by your browser
                on first visit and stored on your device. It contains no personal information and is not used for
                advertising or cross-site tracking.
              </li>
              <li>
                <span className="font-medium">Browser characteristics</span> — a small, non-identifying set of signals
                (such as user-agent string, language, time zone, screen size and platform), combined into a single hash.
              </li>
              <li><span className="font-medium">Activity logs</span> — a record of significant actions taken on an account or a store.</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-semibold text-slate-900">3. Why we use it</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>to provide the platform — create your account, run your store, process orders and payouts;</li>
              <li>to verify vendor identity and prevent fraud;</li>
              <li>
                to detect and stop abuse and enforce the Terms — in particular bulk or automated account creation,
                scraping and bulk downloading, credential sharing, and attempts to reverse-engineer or copy the platform.
                Repeated blocked or suspicious signup attempts from one device may result in that device being
                automatically blocked;
              </li>
              <li>to keep the platform secure (rate limiting, blocking known-bad addresses and devices);</li>
              <li>to send you transactional email (verification, password reset, order and payout notifications);</li>
              <li>to comply with the law and respond to lawful requests.</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-semibold text-slate-900">4. Who we share it with</h2>
            <p>
              We do not sell your personal information. We share only what is necessary with the service providers that
              run the platform: our payment processor (Paystack) to take payments and route payouts, our email provider
              to deliver transactional email, and our hosting and database providers. A vendor and a customer necessarily
              see the order information required to fulfil a sale between them.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-semibold text-slate-900">5. How long we keep it</h2>
            <p>
              Account, store and order records are kept for as long as the account exists and for a reasonable period
              afterwards to meet legal, tax and dispute-resolution obligations. Security and abuse data (connection logs,
              device identifiers, abuse events, ban records) is kept for as long as it is useful for preventing repeat
              abuse, and then removed or anonymised.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-semibold text-slate-900">6. Your rights</h2>
            <p>
              You may request access to the personal information we hold about you, ask us to correct it, or ask us to
              delete your account and associated data (subject to the retention obligations above). Email{" "}
              <a href="mailto:support@ozmictech.com" className="text-brand-600 hover:underline">support@ozmictech.com</a>.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-semibold text-slate-900">7. If your access is restricted</h2>
            <p>
              If your account has been suspended or your device blocked and you believe it was a mistake, you can appeal
              by emailing{" "}
              <a href="mailto:support@ozmictech.com?subject=Account%20appeal" className="text-brand-600 hover:underline">support@ozmictech.com</a>{" "}
              from the email address on the account, describing what happened. We aim to respond within a few business
              days, and will lift the restriction if the appeal is upheld.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-semibold text-slate-900">8. Changes</h2>
            <p>We may update this policy as the platform changes. Continuing to use Storezn after an update means you accept the revised policy.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-semibold text-slate-900">9. Contact</h2>
            <p>
              Questions about this policy can be sent to{" "}
              <a href="mailto:support@ozmictech.com" className="text-brand-600 hover:underline">support@ozmictech.com</a>.
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
